"""
Models package for irl_robotics.

All models are re-exported here for backward compatibility.
New code should import from the specific sub-modules directly.
"""

from .auth import (
    AuthResponse,
    ConfirmRequest,
    ForgotPasswordRequest,
    HuggingFaceTokenRequest,
    LoginCredentialsRequest,
    NetworkCredentials,
    ResetPasswordRequest,
    Session,
    SessionReponse,
    VerifyEmailCodeRequest,
    WandBTokenRequest,
)
from .browse import (
    BrowseFilesResponse,
    BrowserFilesRequest,
    DeleteEpisodeRequest,
    ItemInfo,
)
from .camera import AllCamerasStatus, SingleCameraStatus
from .chat_models import ChatRequest, ChatResponse
from .control import (
    AIControlStatusResponse,
    AIStatusResponse,
    AppControlData,
    AutoControlRequest,
    CalibrateResponse,
    EmoteRequest,
    EndEffectorPosition,
    EndEffectorReadRequest,
    FeedbackRequest,
    JointsReadRequest,
    JointsReadResponse,
    JointsWriteRequest,
    MoveAbsoluteRequest,
    RelativeEndEffectorPosition,
    RobotPairRequest,
    StartAIControlRequest,
    StartLeaderArmControlRequest,
    StartServerRequest,
    TemperatureReadResponse,
    TemperatureWriteRequest,
    TorqueControlRequest,
    TorqueReadResponse,
    VoltageReadResponse,
)
from .dataset import BaseDataset, BaseEpisode, JsonEpisode, Observation, Step
from .lerobot_dataset import (
    BaseRobotInfo,
    EpisodesModel,
    InfoModel,
    LeRobotDataset,
    LeRobotEpisode,
)
from .network import (
    LocalDevice,
    RobotConnectionRequest,
    RobotConnectionResponse,
    ScanDevicesResponse,
    ScanNetworkRequest,
    ScanNetworkResponse,
)
from .recording import (
    DatasetListResponse,
    DatasetRepairRequest,
    DatasetShuffleRequest,
    DatasetSplitRequest,
    HFDownloadDatasetRequest,
    MergeDatasetsRequest,
    RecordingPlayRequest,
    RecordingStartRequest,
    RecordingStopRequest,
    RecordingStopResponse,
)
from .robot import (
    BaseRobot,
    BaseRobotConfig,
    BaseRobotPIDGains,
    RobotConfigResponse,
    RobotConfigStatus,
    Temperature,
)
from .server import (
    AdminSettingsRequest,
    AdminSettingsResponse,
    AdminTokenSettings as AdminSettingsTokenResponse,
    HFWhoamIResponse,
    InfoResponse,
    RobotStatus,
    ServerInfoResponse,
    ServerStatus,
    SpawnStatusResponse,
    StatusResponse,
    VizSettingsResponse,
)
from .teleop import (
    AddZMQCameraRequest,
    TeleopSettings,
    TeleopSettingsRequest,
    UDPServerInformationResponse,
)
from .training import (
    CancelTrainingRequest,
    CustomTrainingRequest,
    ModelConfigurationRequest,
    ModelConfigurationResponse,
    ModelStatusRequest,
    ModelStatusResponse,
    StartTrainingResponse,
    SupabaseTrainingModel,
    TrainingInfoRequest,
    TrainingInfoResponse,
    TrainingsList,
)

__all__ = [
    # auth
    "AuthResponse",
    "ConfirmRequest",
    "ForgotPasswordRequest",
    "HuggingFaceTokenRequest",
    "LoginCredentialsRequest",
    "NetworkCredentials",
    "ResetPasswordRequest",
    "Session",
    "SessionReponse",
    "VerifyEmailCodeRequest",
    "WandBTokenRequest",
    # browse
    "BrowseFilesResponse",
    "BrowserFilesRequest",
    "DeleteEpisodeRequest",
    "ItemInfo",
    # camera
    "AllCamerasStatus",
    "SingleCameraStatus",
    # chat
    "ChatRequest",
    "ChatResponse",
    # control
    "AIControlStatusResponse",
    "AIStatusResponse",
    "AppControlData",
    "AutoControlRequest",
    "CalibrateResponse",
    "EmoteRequest",
    "EndEffectorPosition",
    "EndEffectorReadRequest",
    "FeedbackRequest",
    "JointsReadRequest",
    "JointsReadResponse",
    "JointsWriteRequest",
    "MoveAbsoluteRequest",
    "RelativeEndEffectorPosition",
    "RobotPairRequest",
    "StartAIControlRequest",
    "StartLeaderArmControlRequest",
    "StartServerRequest",
    "TemperatureReadResponse",
    "TemperatureWriteRequest",
    "TorqueControlRequest",
    "TorqueReadResponse",
    "VoltageReadResponse",
    # dataset
    "BaseDataset",
    "BaseEpisode",
    "JsonEpisode",
    "Observation",
    "Step",
    # lerobot_dataset
    "BaseRobotInfo",
    "EpisodesModel",
    "InfoModel",
    "LeRobotDataset",
    "LeRobotEpisode",
    # network
    "LocalDevice",
    "RobotConnectionRequest",
    "RobotConnectionResponse",
    "ScanDevicesResponse",
    "ScanNetworkRequest",
    "ScanNetworkResponse",
    # recording
    "DatasetListResponse",
    "DatasetRepairRequest",
    "DatasetShuffleRequest",
    "DatasetSplitRequest",
    "HFDownloadDatasetRequest",
    "MergeDatasetsRequest",
    "RecordingPlayRequest",
    "RecordingStartRequest",
    "RecordingStopRequest",
    "RecordingStopResponse",
    # robot
    "BaseRobot",
    "BaseRobotConfig",
    "BaseRobotPIDGains",
    "RobotConfigResponse",
    "RobotConfigStatus",
    "Temperature",
    # server
    "AdminSettingsRequest",
    "AdminSettingsResponse",
    "AdminSettingsTokenResponse",
    "HFWhoamIResponse",
    "InfoResponse",
    "RobotStatus",
    "ServerInfoResponse",
    "ServerStatus",
    "SpawnStatusResponse",
    "StatusResponse",
    "VizSettingsResponse",
    # teleop
    "AddZMQCameraRequest",
    "TeleopSettings",
    "TeleopSettingsRequest",
    "UDPServerInformationResponse",
    # training
    "CancelTrainingRequest",
    "CustomTrainingRequest",
    "ModelConfigurationRequest",
    "ModelConfigurationResponse",
    "ModelStatusRequest",
    "ModelStatusResponse",
    "StartTrainingResponse",
    "SupabaseTrainingModel",
    "TrainingInfoRequest",
    "TrainingInfoResponse",
    "TrainingsList",
]
